trigger:
  branches:
    include:
      - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
    - script: './setup_ubuntu.sh'
    - script: './build-qt-wallet-linux.sh'
    - script: './deploy_linux.sh'
  displayName: 'Linux64'
- job: macos
  pool:
    vmImage: macos-10.14
  steps:
    - script: './setup_macos.sh'
    - script: './build-qt-wallet-macos.sh'
    - script: './deploy_macos.sh'
  displayName: 'MacOSX'
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: 'setup_windows.bat'
    - script: 'build-qt-wallet-windows.bat'
    - script: 'deploy_windows.bat'
  displayName: 'Windows64'
- job: windows32
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: 'setup_windows32.bat'
    - script: 'build-qt-wallet-windows32.bat'
    - script: 'deploy_windows32.bat'
  displayName: 'Windows32'
