trigger:
  branches:
    include:
      - master

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
    - script: './setup_ubuntu.sh'
    - script: './build-qt-wallet-linux.sh'
- job: windows
  pool:
    vmImage: windows-latest
  steps:
    - script: 'build-qt-wallet-windows.bat'
