# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
      echo Building project
      ./setup_ubuntu.sh
      ./build-qt-wallet-linux.sh qmake
    displayName: 'Setup, Build, and Confirm'
- job: windows
  pool:
    vmImage: windows-lastest
  steps:
    -script: |
      echo Buildiing project
      build-qt-wallet-windows.bat
    displayName: 'Setup, Build, and Confirm'

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
