# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: './setup_ubuntu.sh'
    - script: './build-qt-wallet-linux.sh qmake'
- job: windows
  pool:
    vmImage: windows-lastest
  steps:
    -script: 'build-qt-wallet-windows.bat'

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
