trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      setupName: 'setup-ubuntu.sh'
      scriptName: 'build-qt-wallet-linux.sh'
    windows:
      imageName: 'windows-latest'
      setupName: 'setup-windows.bat'
      scriptName: 'build-qt-wallet-windows.bat'

pool:
  vmImage: $(imageName)

steps:

- script: |
  $(setupName)
  $(scriptName)

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
