trigger:
  branches:
    include:
      - master

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
    - script: './setup_ubuntu.sh'
    - script: './build-qt-wallet-linux.sh'
  displayName: 'Setup, Build, and Confirm - Linux64'
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: 'setup_windows.bat'
    - script: 'build-qt-wallet-windows.bat'
  displayName: 'Setup, Build, and Confirm - Windows64'
